### ISSUE TITLE
Alias the property `background` with `bg`

### ISSUE THREAD

**Issue by remorses** [smooth-code/xstyled#89]
## 🚀 Feature Proposal

Use `bg` as an alias of `background`

## Motivation

`bg` is shorteer than `background` and easier to transition from `styled-system` that already implements it

## Example

```tsx
function App() {
    return (
        <Box bg='red'>
        </Box>
    )
}
```

## Pitch

Faster development and less code

**Comment by gregberge** [comment]
Hello @remorses, I don't think having to learn a new language to use xstyled is a good thing. We add alias for `margin` and `padding` because it is very commonly used especially in grids. But `background` is not a common property that you use everywhere.

Also `background` and `backgroundColor` does not have the same treatment. So it could be confusing.

I think it is a bad choice from `styled-system` to alias it. Let's see if other users want it!

**Comment by gregberge** [comment]
@P1X3L @theo-mesnil, your advice on this one?

**Comment by theo-mesnil** [comment]
Hey ! 

Maybe is not the best choice from styled system but, if this exist on styled system, it's better to have it on xstyled :)

**Comment by P1X3L** [comment]
I would add `bg` AND `bgColor` to avoid any confusion.
`bg` would be the alias of `background`
`bgColor` the alias of `backgroundColor`

**Comment by seeden** [comment]
I migrated from styled-system/rebass and was surprised why my "bg" not working :) I can live without it but I like this property as well.

**Comment by gregberge** [comment]
OK, could someone make the PR to alias `backgroundColor` to `bg`?

**Comment by gregberge** [comment]
@P1X3L @theo-mesnil we will stick to styled-system.
